### ISSUE TITLE
`sync': undefined method `join' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by ThePixelDeveloper** [EugenMayer/docker-sync-boilerplate#1]
Tried syncing with Unison and got the following error:

```
/Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.7/lib/docker_sync/sync_strategy/unison.rb:38:in `sync': undefined method `join' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.7/lib/docker_sync/sync_strategy/unison.rb:93:in `start_container'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.7/lib/docker_sync/sync_strategy/unison.rb:32:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.7/lib/docker_sync/sync_process.rb:64:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.7/lib/docker_sync/sync_manager.rb:103:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.7/lib/docker_sync/sync_manager.rb:102:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.7/lib/docker_sync/sync_manager.rb:102:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.7/tasks/sync.thor:32:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Library/Ruby/Gems/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/docker-sync-0.0.7/bin/docker-sync:11:in `<top (required)>'
	from /usr/local/bin/docker-sync:23:in `load'
	from /usr/local/bin/docker-sync:23:in `<main>'
```

``` yml
syncs:
    appcode:
        src: '.'
        dest: '/var/www'
        sync_host_ip: 'localhost'
        sync_host_port: 10871
        sync_strategy: 'unison'
```

**Comment by EugenMayer** [comment]
Please install 0.0.8 there was an issue introduced in the last commit before releasing 0.0.7 - sorry.
